# Generated by Django 4.0.6 on 2022-07-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='ingredients',
            field=models.ManyToManyField(to='main.object'),
        ),
    ]
